### ISSUE TITLE
update KDE runtime to 5.12

### ISSUE THREAD

**Issue by eszlari** [flathub/org.equeim.Tremotesf#1]

**Comment by equeim** [comment]
5.12 runtime has some issues with icon themes. I don't know what is causing this issue, but with 5.12 runtime Tremotesf can't find host icon theme. With 5.11 everything works fine.

**Comment by eszlari** [comment]
Okay, just remember that 5.11 is EOL: https://github.com/KDE/flatpak-kde-runtime/commit/4d7a8d72983d9e86f5f5ce46d3524544c0ee6abe
(Maybe that feature is not as important)
